apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: doubler
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/hsctf3/doubler-challenge:e998a64a2da204652880783f919a19d7cd7080284f7cb1bff47fa584bb2edac4
