apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: fancier-page
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        targetPort: 80
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/hsctf2/fancier-page-challenge:a608bb80df60953b6b4784f65f23f80b3ddb8170ec916684b256f87209075f42
