apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: banana-queries
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/amiable-fin-385804/banana-queries-challenge:fe73565a944daec9d7369506043b31daf88315ea5bce35ef79bd756ae3fcc46d
