apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: very-secure
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        targetPort: 80
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/hsctf2/very-secure-challenge:117ab4b5daeca6120dd6f4ef282dbf6e550347d9edb3e9d6adabdb6c2a1b4e14
