apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: ex
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/amiable-fin-385804/ex-challenge:6bbb9023f890f6d98db84245ff66128ebfbebcf2378a58a202b7450effd11505
