apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: mogodb
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        targetPort: 80
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/hsctf2/mogodb-challenge:5d8c8788b4ca16ba58a618eb2ed1c192c83d81b9760529b058ff35b7502dc71d
