apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: xor-trickery
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/amiable-fin-385804/xor-trickery-challenge:49e250aea7e082fe4962fd1e82e3e14874424e376d5fb8da6706e1904907637b
